--CREATE USER SA PASSWORD ""

--GRANT DBA TO SA

SET WRITE_DELAY 10

SET SCHEMA PUBLIC

INSERT INTO USERS VALUES(1, 'jon','password123', 'jon@pelipas.com')
INSERT INTO USERS VALUES(2, 'issa','password345', 'issa@pelipas.com')
INSERT INTO USERS VALUES(3, 'zoe','password567', 'zoe@pelipas.com')

INSERT INTO CUSTOMER VALUES(1, 'Jon','Pelipas')
INSERT INTO CUSTOMER VALUES(2, 'Marissa','Pelipas')
INSERT INTO CUSTOMER VALUES(3, 'Zoe','Pelipas')

INSERT INTO ADDRESS VALUES(1, '8 BurnAu St','Apt 6','Salem','MA', '01701', 1)
INSERT INTO ADDRESS VALUES(2, '6 Elmo St','Apt 9','Natick','MA', '01702', 2)

INSERT INTO ADDRESS VALUES(3, '8 Bios St','Apt 5','Boston','MA', '01702', 2)


--INSERT INTO CATEGORY VALUES(1,'Fruit')
--
--INSERT INTO CATEGORY VALUES(2,'Vegetables')
--
--INSERT INTO CATEGORY VALUES(3,'Meat')
--
--INSERT INTO CATEGORY VALUES(4,'Dairy')
--
--INSERT INTO CATEGORY VALUES(5,'Organic')

INSERT INTO PRODUCT VALUES(1,'Apple',0.25E0,'Fresh Apple')

INSERT INTO PRODUCT VALUES(2,'Orange',0.3E0,'Fresh Orange')

INSERT INTO PRODUCT VALUES(3,'Banana',0.75E0,'Sweet Philippine Banana')

INSERT INTO PRODUCT VALUES(4,'Peas',1.5E0,'Dozen Peas from USA')

INSERT INTO PRODUCT VALUES(5,'Carrots',1.00,'Carrots from Mexico')

INSERT INTO PRODUCT VALUES(6,'Organic Apple',0.75,'Organic Apple from Alps')

--INSERT INTO PRODUCT_CATEGORIES VALUES(1,1)
--
--INSERT INTO PRODUCT_CATEGORIES VALUES(2,1)
--
--INSERT INTO PRODUCT_CATEGORIES VALUES(3,1)
--
--INSERT INTO PRODUCT_CATEGORIES VALUES(4,2)
--
--INSERT INTO PRODUCT_CATEGORIES VALUES(5,2)
--
--INSERT INTO PRODUCT_CATEGORIES VALUES(6,1)
--
--INSERT INTO PRODUCT_CATEGORIES VALUES(6,5)